services:
  app-web-chatapp:
    image: node:22
    container_name: app-web-chatapp
    working_dir: /app
    volumes:
      - ./App/AppWeb:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - api-chatapp
      - db-chatapp
    env_file:
      - ./App/AppWeb/.env.local
    networks:
      - networkChatApp

  api-chatapp:
    image: node:22
    container_name: api-chatapp
    working_dir: /app
    volumes:
      - ./API:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - db-chatapp
    env_file:
      - ./API/.env
    networks:
      - networkChatApp

  db-chatapp:
    image: postgres:13
    container_name: db-chatapp
    env_file:
      - ./DB/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - networkChatApp

volumes:
  postgres-data:

networks:
  networkChatApp:
    driver: bridge
    name: networkChatApp